---
title: "solar2"
author: "Kaiwei Xiao"
date: "2023-04-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
solar = read.csv("spg.csv")
#make this example reproducible
set.seed(1)

#use 70% of dataset as training set and 30% as test set
sample <- sample(c(TRUE, FALSE), nrow(solar), replace=TRUE, prob=c(0.7,0.3))
train  <- solar[sample, ]
test   <- solar[!sample, ]
```

```{r}
x <- data.matrix(train[,1:20])
y = train$generated_power_kw

library(glmnet)
cv_model <- cv.glmnet(x, y, alpha = 1)

#find optimal lambda value that minimizes test MSE
best_lambda <- cv_model$lambda.min
best_lambda
```

```{r}
best_model <- glmnet(x, y, alpha = 1, lambda = best_lambda)
coef(best_model)
```


```{r}
train.x <- data.frame(train[,1:20])
train.y = train$generated_power_kw
mod = lm(train$generated_power_kw~., data = train)
summary(mod)
plot(mod)
hist(train$generated_power_kw)
```

```{r}

mse = function(
    predict,actual){
 mean((predict-actual)^2)
}
```

```{r}
test.x = data.frame(test[,1:20])
test.y = data.frame(test$generated_power_kw)
pre = predict(mod, newdata = test.x)
sum((pre-test.y)^2)/length(pre)
mse(pre,test.y)
```

```{r}
pbinom(0.5,7,1/3,lower.tail = F)
?dbinom
```

